### ISSUE TITLE
Problems with Java 11

### ISSUE THREAD

**Issue by sevenstarknight** [codemercenary/JMatIO#4]
Hi,
I have been using JMatIO successfully with Java 8, however I recently attempted to transition to Java 11 and am now getting this error

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jmatio.io.MatFileReader$1 (file: /.m2/repository/com/diffplug/matsim/matfilerw/3.0.1/matfilerw-3.0.1.jar) to method java.nio.DirectByteBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of com.jmatio.io.MatFileReader$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/Cleaner
	at com.jmatio.io.MatFileReader$1.run(MatFileReader.java:691)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.jmatio.io.MatFileReader.clean(MatFileReader.java:684)
	at com.jmatio.io.MatFileReader.read(MatFileReader.java:389)
	at com.jmatio.io.MatFileReader.read(MatFileReader.java:313)
	at com.jmatio.io.MatFileReader.<init>(MatFileReader.java:174)
	at com.jmatio.io.MatFileReader.<init>(MatFileReader.java:150)

I didn't know if anyone else has looked into this. Thanks

**Comment by nedtwigg** [comment]
No one is maintaining JMatIO.  https://github.com/diffplug/matfilerw has the same API, and is getting some maintenance.  https://github.com/ennerf/MatlabTools is a new project under active development.

**Comment by siri-ius** [comment]
Is it fixed now?

**Comment by nedtwigg** [comment]
This project is still not being maintained.  https://github.com/diffplug/matfilerw is being maintained, probably it works there, but no guarantees.  https://github.com/HebiRobotics/MFL is even better, but it has a different API.

**Comment by siri-ius** [comment]
Thank you!
